// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Game_Sprite.tsx";
import * as $$2 from "./islands/Game_Tile.tsx";
import * as $$3 from "./islands/keyBoard.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Game_Sprite.tsx": $$1,
    "./islands/Game_Tile.tsx": $$2,
    "./islands/keyBoard.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
